# - Try to find the LDAP client libraries
# Once done this will define
#
#  LDAP_FOUND - system has libldap
#  LDAP_INCLUDE_DIR - the ldap include directory
#  LDAP_LIBRARIES - libldap + liblber (if found) library
#  LBER_LIBRARIES - liblber library
#
IF(LDAP_INCLUDE_DIR AND LDAP_LIBRARIES)
  # Already in cache, be silent
  SET(LDAP_FIND_QUIETLY TRUE)
ENDIF(LDAP_INCLUDE_DIR AND LDAP_LIBRARIES)
#
FIND_PATH(LDAP_INCLUDE_DIR ldap.h)
FIND_LIBRARY(LDAP_LIBRARIES NAMES ldap)
FIND_LIBRARY(LBER_LIBRARIES NAMES lber)
#
IF(LDAP_INCLUDE_DIR AND LDAP_LIBRARIES)
  SET(LDAP_FOUND TRUE)
  IF(LBER_LIBRARIES)
    SET(LDAP_LIBRARIES ${LDAP_LIBRARIES} ${LBER_LIBRARIES})
  ENDIF(LBER_LIBRARIES)
ENDIF(LDAP_INCLUDE_DIR AND LDAP_LIBRARIES)
#
IF(LDAP_FOUND)
  IF(NOT LDAP_FIND_QUIETLY)
    MESSAGE(STATUS "Found LDAP library: ${LDAP_LIBRARIES}")
    MESSAGE(STATUS "Found LDAP includes: ${LDAP_INCLUDE_DIR}")
  ENDIF(NOT LDAP_FIND_QUIETLY)
ELSE(LDAP_FOUND)
  IF (LDAP_FIND_REQUIRED)
    MESSAGE(FATAL_ERROR "Could NOT find LDAP")
  ENDIF (LDAP_FIND_REQUIRED)
ENDIF(LDAP_FOUND)
#
MARK_AS_ADVANCED(LDAP_INCLUDE_DIR LDAP_LIBRARIES LBER_LIBRARIES)
#
